stages:
  - build
  - release

build:
  stage: build
  image: gcc
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  tags:
    - build
  script:
    - echo "Start job (id=$CI_JOB_ID)"
    - sha_short=$(git rev-parse --short HEAD)
    - echo "BUILD_JOB_ID=${CI_JOB_ID}" >> variables.env
    - echo "BUILD_SHA_SHORT=${sha_short}" >> variables.env
    - cat variables.env
    - git submodule init
    - git submodule update

  artifacts:
    reports:
      dotenv: variables.env
    paths:
      - build

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: 
    - job: "build"
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  script:
    - echo "Running release for $CI_COMMIT_TAG"
  # release:
  #   name: 'Release $TAG $CI_COMMIT_TAG-$BUILD_SHA_SHORT'
  #   tag_name: '$CI_COMMIT_TAG'
  #   description: CHANGELOG.md
  #   ref: '$CI_COMMIT_SHA'
  #   assets:
  #     links:
  #       - name: 'Binaries'
  #         url: '$CI_PROJECT_URL/-/jobs/$BUILD_JOB_ID/artifacts/download?file_type=archive'
